### ISSUE TITLE
Incremental fails to get version from egg package

### ISSUE THREAD

**Issue by felipedau** [hawkowl/incremental#30]
I am not aware of the current status of the egg-wheel transition thing and how relevant this issue is, but incremental fails to get the version of a package's egg because it did not expect it to be an `.egg` (or is not supposed to be used for that?). One of the consequences is that it won't allow any package (or its dependencies) to use Twisted's `@deprecated` if the `Version` provided is from an egg package.

unMessage is a package that depends on txtorcon and it is not possible to install it with `python setup.py install` (reported in AnemoneLabs/unmessage#29) because txtorcon uses `@deprecated` and is installed as an egg.

I think the easiest way to reproduce this is installing txtorcon with easy_install:

```bash
$ sudo easy_install txtorcon
$ python
```
```python
>>> import txtorcon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/txtorcon/__init__.py", line 16, in <module>
  File "build/bdist.linux-x86_64/egg/txtorcon/controller.py", line 34, in <module>
  File "build/bdist.linux-x86_64/egg/txtorcon/torconfig.py", line 34, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/python/deprecate.py", line 293, in deprecationDecorator
    function, version, None, replacement)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/python/deprecate.py", line 238, in getDeprecationWarningString
    _fullyQualifiedName(callableThing), version, format, replacement)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/python/deprecate.py", line 198, in _getDeprecationWarningString
    'version': getVersionString(version)}
  File "/usr/local/lib/python2.7/dist-packages/incremental-16.10.1-py2.7.egg/incremental/__init__.py", line 518, in getVersionString
    result = '%s %s' % (version.package, version.short())
  File "/usr/local/lib/python2.7/dist-packages/incremental-16.10.1-py2.7.egg/incremental/__init__.py", line 221, in short
    gitver = self._getGitVersion()
  File "/usr/local/lib/python2.7/dist-packages/incremental-16.10.1-py2.7.egg/incremental/__init__.py", line 411, in _getGitVersion
    if ".git" in os.listdir(upOne):
OSError: [Errno 20] Not a directory: '/usr/local/lib/python2.7/dist-packages/txtorcon-0.19.1-py2.7.egg'
```

This was reproduced on a Debian jessie with the following installed:

```
build-essential/stable,now 11.7 amd64 [installed]
libffi-dev/stable,now 3.1-2+b2 amd64 [installed]
libssl-dev/stable,now 1.0.1t-1+deb8u6 amd64 [installed]
python/stable,now 2.7.9-1 amd64 [installed]
python-dev/stable,now 2.7.9-1 amd64 [installed]
python-pyasn1/jessie-backports,now 0.1.9-1~bpo8+1 all [installed]
python-setuptools/jessie-backports,now 33.1.1-1~bpo8+1 all [installed]
```

Thanks!

**Comment by hawkowl** [comment]
Fixed in #33
