### ISSUE TITLE
_getGitVersion failure when installs with pip from a branch

### ISSUE THREAD

**Issue by adiroiban** [hawkowl/incremental#32]
I get this on both python2 and python3 on Ubuntu 16/04

Here are the steps to reproduce:

```
virtualenv --python=python3 9083-twisted-dev/
cd 9083-twisted-dev/
. bin/activate
pip install "git+https://github.com/buildbot/buildbot@v0.9.5#subdirectory=pkg"
pip install "git+https://github.com/buildbot/buildbot@v0.9.5#subdirectory=master"
pip install "git+https://github.com/buildbot/buildbot@v0.9.5#subdirectory=worker"
pip install --upgrade "git+https://github.com/twisted/twisted"
pip install --upgrade "git+https://github.com/twisted/twisted@9083-rodrigc-version"
```

I end up with this traceback

```
$ buildbot create-master
Traceback (most recent call last):
  File "/home/adi/tmp/9083-twisted-dev/bin/buildbot", line 11, in <module>
    load_entry_point('buildbot==0.9.5', 'console_scripts', 'buildbot')()
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/buildbot/scripts/runner.py", line 757, in run
    subcommandFunction = reflect.namedObject(subconfig.subcommandFunction)
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/twisted/python/reflect.py", line 166, in namedObject
    module = namedModule('.'.join(classSplit[:-1]))
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/twisted/python/reflect.py", line 152, in namedModule
    topLevel = __import__(name)
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/buildbot/scripts/create_master.py", line 30, in <module>
    from buildbot.master import BuildMaster
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/buildbot/master.py", line 39, in <module>
    from buildbot.buildbot_net_usage_data import sendBuildbotNetUsageData
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/buildbot/buildbot_net_usage_data.py", line 36, in <module>
    from buildbot.process.buildstep import _BuildStepFactory
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/buildbot/process/buildstep.py", line 261, in <module>
    util.ComparableMixin):
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/buildbot/process/buildstep.py", line 380, in BuildStep
    @deprecate.deprecated(versions.Version("buildbot", 0, 9, 0))
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/twisted/python/deprecate.py", line 293, in deprecationDecorator
    function, version, None, replacement)
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/twisted/python/deprecate.py", line 238, in getDeprecationWarningString
    _fullyQualifiedName(callableThing), version, format, replacement)
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/twisted/python/deprecate.py", line 198, in _getDeprecationWarningString
    'version': getVersionString(version)}
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/incremental/__init__.py", line 518, in getVersionString
    result = '%s %s' % (version.package, version.short())
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/incremental/__init__.py", line 221, in short
    gitver = self._getGitVersion()
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/incremental/__init__.py", line 422, in _getGitVersion
    return self._parseGitDir(os.path.join(upOneMore, '.git'))
  File "/home/adi/tmp/9083-twisted-dev/lib/python3.5/site-packages/incremental/__init__.py", line 389, in _parseGitDir
    with open(headFile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/adi/.git/HEAD'
```

**Comment by hawkowl** [comment]
Fixed in #33
